# Generated by Django 4.0.5 on 2024-11-12 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('RecipeId', models.AutoField(primary_key=True, serialize=False)),
                ('RecipeName', models.CharField(max_length=50)),
                ('Origin', models.CharField(max_length=200)),
                ('Ingredients', models.CharField(max_length=200)),
                ('image', models.FileField(upload_to='images/')),
                ('rating', models.FloatField(default=0)),
                ('duration', models.CharField(max_length=3)),
                ('likes', models.JSONField(default=list)),
                ('comments', models.JSONField(default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
