# Generated by Django 4.0.5 on 2024-11-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='comments',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='likes',
            field=models.JSONField(blank=True),
        ),
    ]
