# Generated by Django 5.1.3 on 2024-11-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeApp', '0005_alter_recipe_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='Procedure',
            field=models.TextField(default=''),
        ),
    ]
